name = "BluseDB"
uuid = "ad29d749-1a85-45fa-99eb-ec15dfcb1cc5"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.1.0"

[deps]
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
