# This YAML file contains a list of MySQL DDL statements that will create the
# database tables for the BluseDB database.  These statements should be
# executed in order.
---
- >-
  create table if not exists observations (
    `id` int not null auto_increment,
    `start` datetime not null,
    `imjd` int not null,
    `smjd` int not null,
    `ra` double not null,
    `dec` double not null,
    `src_name` varchar(256) not null,
    `fecenter` double not null,
    `fenchan` int not null,
    `nants` int not null,
    `dwell` double not null,
    primary key(id)
  )

- >-
  create table if not exists rawfiles (
    `id` int not null auto_increment,
    `observation_id` int not null,
    `obsfreq` double not null,
    `obsbw` double not null,
    `nchan` int not null,
    `host` varchar(256) not null,
    `dir` varchar(4096) not null,
    `file` varchar(1024) not null,
    primary key(id),
    foreign key (observation_id)
      references observations(id)
  )
